### ISSUE TITLE
error on issue_heading

### ISSUE THREAD

**Issue by undigo** [spike008t/redmine_advanced_issues#2]
Hi,
an error occured when opened issue :

Processing IssuesController#show (...) [GET]
  Parameters: {"action"=>"show", "id"=>"68", "controller"=>"issues"}
Rendering template within layouts/base
Rendering issues/show.rhtml

ActionView::TemplateError (undefined method `issue_heading' for #ActionView::Base:0x6428658) on line #7 of vendor/plugins/redmine_advanced_issues/app/views/issues/show.rhtml:
4: 
5: <%= render :partial => 'action_menu' %>
6: 
7: <h2><%= l(:label_warning_risk) if @issue.has_risk? %> <%= issue_heading(@issue) %></h2>
8: 
9: <div class="<%= @issue.css_classes %> details">
10:     <%= avatar(@issue.author, :size => "50") %>

```
vendor/plugins/redmine_advanced_issues/app/views/issues/show.rhtml:7:in `_run_rhtml_vendor47plugins47redmine_advanced_issues47app47views47issues47show46rhtml'
app/controllers/issues_controller.rb:117
app/controllers/issues_controller.rb:116:in `show'
```

Rendering D:/BitNami Redmine Stack/apps/redmine/public/500.html (500 Internal Server Error)

**Comment by spike008t** [comment]
could you give me your version of redmine?

**Comment by undigo** [comment]
Hi,
My version is 1.1.2 but I could resolve the template error with the search
engine on redmine official site where I search "issue_heading" and see the
diff between twice trunk version of 2 files
I complete manually these 2 files  \redmine\app\views\issues\show.rhtml
and \redmine\app\helpers\issues_helper.rb and all it done !

Le 22 sept. 2011 21:04, "spike008t" <
reply@reply.github.com> a
crit :

**Comment by spike008t** [comment]
ok, that sound great!

Have you done a patch? that could great if you can send it to me?
