### ISSUE TITLE
Redmine 2.1.2 - "Missing template, responding with 404" Error Message

### ISSUE THREAD

**Issue by a-herbe** [spike008t/redmine_advanced_issues#8]
In release 2.1.2 of Redmine, after fix "link_to_remote" method calls to "link_to" ones, the plugin load but, like some others plugins, "Missing template, responding with 404" error messages shows when accessing plugin configure page.

Do you have any idea to patch or fix it qeekly ?

Started GET "/settings/plugin/redmine_advanced_issues" for 127.0.0.1 at 2012-10-
18 19:19:27 +0200
Processing by SettingsController#plugin as HTML
  Parameters: {"id"=>"redmine_advanced_issues"}
  Current user: a-herbe (id=3)
  Rendered plugins/redmine_banner/app/views/settings/plugin.html.erb within layouts/admin (0.0ms)
Missing template, responding with 404
  Rendered common/error.html.erb within layouts/base (0.0ms)
  Rendered plugins/redmine_banner/app/views/banner/_project_body_bottom.html.erb (0.0ms)
  Rendered plugins/redmine_banner/app/views/banner/_body_bottom.html.erb (0.0ms)
  Rendered plugins/redmine_banner/app/views/banner/_after_top_menu.html.erb (0.0ms)
Completed 404 Not Found in 125ms (Views: 125.0ms | ActiveRecord: 0.0ms)

Thanks in advance and great job.

**Comment by rudrud** [comment]
+1

**Comment by a-herbe** [comment]
It seems that it could be solved like many others plugins in 2.x branch of Redmine, with changing extension of *.rhtml files to *.html.erb.

**Comment by spike008t** [comment]
Thank you.
I'm working on it (I was so busy...) Sorry.

I'm working with 2.1.x compatibility.
I've found news bugs (because ruby 1.9 is not the same as before...).

I'll push a new update soon! Stay in touch.

**Comment by a-herbe** [comment]
Thank you very much... I'll give you feedbacks, if we found others bugs.
